return {
	"ray-x/lsp_signature.nvim",
	event = "VeryLazy",
	opts = {
		bind = true,
		doc_lines = 10,
		floating_window = true,
		fix_pos = true,
		hint_enable = true,
		hint_prefix = ":3 ",
		hint_scheme = "Statement",
		max_height = 12,
		max_width = 120,
		noice = false,
		offset_y = 0,
		on_attach = nil,
		padding = " ",
		shadow_blend = 36,
		shadow_guibg = "Black",
		timer_interval = 200,
		toggle_key = "<C-k>",
		toggle_key_flip_floatwin_setting = false,
		transparency = nil,
		transparen_lines = false,
		transparen_padding = 2,
		use_lspsaga = false,
		window_gravity = "cursor",
		wrap = true,
		zindex = 200,
	},
	config = function(_, opts)
		require("lsp_signature").setup(opts)
	end,
}
